### ISSUE TITLE
CLASE 1 (PYTHON) -  Excepciones

### ISSUE THREAD

**Issue by eugenia1984** [CodeSystem2022/ERROR-404-LABORATORIO3#1]
- Crear la carpeta **PYTHON** para tener en ella todos los ejercicios en dicho lenguaje.

- Dentro de la misma crear la carpeta **clase1-excepciones** y subir todos los ejercicios de la clase.

**Comment by eugenia1984** [comment]
Se hizo todo y se mergeo la rama

**Comment by eugenia1984** [comment]
- Lo cerre por error, estaba haciendo la clase 1 pero de JS

**Comment by brianahumada** [comment]
Clase 1 python excepciones, creó la rama para subir los proyectos.

**Comment by brianahumada** [comment]
primera clase ya se subió con éxito.

**Comment by eugenia1984** [comment]
Se cierra el issue porque ya fue mergeado
