### ISSUE TITLE
CLASE 2 (PYTHON) - Manejo de Archivos

### ISSUE THREAD

**Issue by eugenia1984** [CodeSystem2022/ERROR-404-LABORATORIO3#2]
Dentro de la carpeta **PYTHON**  crear la carpeta **clase2-manejo-archivos** y subir todos los ejercicios de la clase.

**Comment by brianahumada** [comment]
creo rama para subir clase 2 de python. Manejo de archivos.

**Comment by eugenia1984** [comment]
Se mergeo la rama a main
