### ISSUE TITLE
Clase 7 - JavaScript - Clases Parte 2

### ISSUE THREAD

**Issue by matias9486** [CodeSystem2022/ERROR-404-LABORATORIO3#21]
Clase 7 de JavaScript. Continuación del tema Clases

**Comment by matias9486** [comment]
Se creó rama: feature/#21-clase7-js-clases-parte2  para subir lo visto en clase.

**Comment by matias9486** [comment]
Trabajo listo para ser revisado.

**Comment by eugenia1984** [comment]
- Ya fue mergeado, se cierra el issue
